Repository hwsuk/discord-bot, pull requests merged in 2021-02, with the labels that each got.

#44 bug(config.json): Update config.json with current role IDs and flair text
  config.json
Labels: bug

#45 feat/react_report: Add message reporting by adding "⚠️" reaction
  config.json
  unity_cogs/notes.py
  unity_cogs/react_report.py
  unity_util/bot_config.py
Labels: enhancement

#50 Add CI workflows
  .flake8
  .github/workflows/black.yml
  .github/workflows/flake8.yml
  README.md
  bot.py
  pyproject.toml
  unity_cogs/cex.py
  unity_cogs/ebay.py
  unity_cogs/limiter.py
  unity_cogs/rendermeme.py
  unity_cogs/usl.py
  unity_cogs/verify.py
  unity_util/embed_helper.py
Labels: CI
